version: "2"
services:
  web:
    image: asmt06
    volumes:
     - .:/work/
     - /work/node_modules
    ports:
     - "3000:3000"
    links:
     - mongo
  mongo:
   image: mongo:4.0.2
   ports:
     - "27017:27017"
   volumes:
     - mongo_data:/data/db

volumes:
  mongo_data:
